security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        siscofac_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /principal
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_token
                csrf_token_id: siscofac_authenticate
            logout:
                path:   /logout
                target: /login  
            provider: siscofac_db_provider

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #Para los usuarios IS_AUTHENTICATED_ANONYMOUSLY
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        #Para los usuarios IS_AUTHENTICATED_FULLY o ROLE_CONSULTOR
        - { path: ^/user/*/show, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^contrato/*/contrato/show, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^contrato/*/suplemento/show, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^contrato/*/factura/show, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^contrato/index, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^suplemento/*/index, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^suplemento/*/*/show, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^factura/*/index, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }
        - { path: ^factura/*/*/show, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO, ROLE_ECONOMICO, ROLE_CONSULTOR] }

        #Para los usuarios ROLE_ECONOMICO
        - { path: ^/factura/*/new, roles: [ROLE_ADMINISTRADOR, ROLE_ECONOMICO] }
        - { path: ^/factura/*/*/edit, roles: [ROLE_ADMINISTRADOR, ROLE_ECONOMICO] }

        #Para los usuarios ROLE_JURIDICO
        - { path: ^/nom/proveedor/*, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/nom/banco/*, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/nom/area/*, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/suplemento/comite/contratacion/*, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/contrato/comite/contratacion/*, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/contrato/new, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/contrato/edit/*, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/suplemento/*/new, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }
        - { path: ^/suplemento/*/*/edit, roles: [ROLE_ADMINISTRADOR, ROLE_JURIDICO] }

        #Para los usuarios ROLE_ADMINISTRADOR
        - { path: ^/conf/*, roles: ROLE_ADMINISTRADOR }
        - { path: ^/user/index, roles: ROLE_ADMINISTRADOR }
        - { path: ^/user/*/edit, roles: ROLE_ADMINISTRADOR }
        - { path: ^/nom/provincia/*, roles: ROLE_ADMINISTRADOR }
        - { path: ^/nom/tipo/persona/*, roles: ROLE_ADMINISTRADOR }
        - { path: ^/nom/tipo/servicio/*, roles: ROLE_ADMINISTRADOR }